default_context:
  project_name: 'network'
  project_slug: 'network'
  domain_main: 'network.com'
  domain_staging: 'stag.network.com'
  docker_swarm_stack_name_main: 'network-com'
  docker_swarm_stack_name_staging: 'stag-network-com'
  secret_key: 'bb7b54e5c6e681d9d91192e436be6046b2eb39cbbe217d47bc63ac2bc3af1afd'
  first_superuser: 'admin@network.com'
  first_superuser_password: 'rootroot'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.network.com", "https://stag.network.com", "https://network.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@network.com'
  postgres_password: 'rootroot'
  pgadmin_default_user: 'admin@network.com'
  pgadmin_default_user_password: 'rootroot'
  traefik_constraint_tag: 'network.com'
  traefik_constraint_tag_staging: 'stag.network.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:rootroot'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend_1'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
