"""init

Revision ID: 797902b5b187
Revises: 
Create Date: 2024-08-23 00:17:10.984725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '797902b5b187'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cost_types',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('divisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('photo', sa.String(), nullable=True),
    sa.Column('is_actual', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('fault_category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('reason_fault',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('statuses',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sub_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('type_objects',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('types_acts',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('types_contracts',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('working_specialty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('director_name', sa.String(), nullable=True),
    sa.Column('cont_phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('cont_address', sa.String(), nullable=True),
    sa.Column('photo', sa.String(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('site', sa.String(), nullable=True),
    sa.Column('is_actual', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('factories_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_object_id', sa.Integer(), nullable=True),
    sa.Column('factory', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['type_object_id'], ['type_objects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type_object_id', 'factory', 'model', name='_type_object_factory_model_uc')
    )
    op.create_table('acts_bases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factory_model_id', sa.Integer(), nullable=True),
    sa.Column('type_act_id', sa.Integer(), nullable=True),
    sa.Column('step_list', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['factory_model_id'], ['factories_models.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['type_act_id'], ['types_acts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('factory_model_id', 'type_act_id', name='_type_act_factory_model_uc')
    )
    op.create_table('contact_persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('photo', sa.String(), nullable=True),
    sa.Column('is_actual', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('validity_period', sa.Date(), nullable=True),
    sa.Column('type_contract_id', sa.Integer(), nullable=True),
    sa.Column('cost_type_id', sa.Integer(), nullable=True),
    sa.Column('file', sa.String(), nullable=True),
    sa.Column('is_actual', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cost_type_id'], ['cost_types.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['type_contract_id'], ['types_contracts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('universal_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('contact_phone', sa.String(), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('photo', sa.String(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('working_specialty_id', sa.Integer(), nullable=True),
    sa.Column('identity_card', sa.String(), nullable=True),
    sa.Column('division_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('qualification_file', sa.String(), nullable=True),
    sa.Column('date_of_employment', sa.Date(), nullable=True),
    sa.Column('is_actual', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['working_specialty_id'], ['working_specialty.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', 'is_actual', name='_email_is_actual_uc')
    )
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('director_id', sa.Integer(), nullable=True),
    sa.Column('phone_office', sa.String(), nullable=True),
    sa.Column('phone_dispatcher', sa.String(), nullable=True),
    sa.Column('phone_accountant', sa.String(), nullable=True),
    sa.Column('photo', sa.String(), nullable=True),
    sa.Column('site', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('is_actual', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['director_id'], ['universal_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('objects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('division_id', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('factory_model_id', sa.Integer(), nullable=True),
    sa.Column('factory_number', sa.String(), nullable=True),
    sa.Column('registration_number', sa.String(), nullable=True),
    sa.Column('number_of_stops', sa.Integer(), nullable=True),
    sa.Column('lifting_heights', sa.Integer(), nullable=True),
    sa.Column('load_capacity', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('cost_nds', sa.Integer(), nullable=True),
    sa.Column('cost_no_nds', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('contact_person_id', sa.Integer(), nullable=True),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('date_inspection', sa.Date(), nullable=True),
    sa.Column('planned_inspection', sa.Date(), nullable=True),
    sa.Column('period_inspection', sa.Date(), nullable=True),
    sa.Column('foreman_id', sa.Integer(), nullable=True),
    sa.Column('mechanic_id', sa.Integer(), nullable=True),
    sa.Column('letter_of_appointment', sa.String(), nullable=True),
    sa.Column('acceptance_certificate', sa.String(), nullable=True),
    sa.Column('act_pto', sa.String(), nullable=True),
    sa.Column('geo', sa.String(), nullable=True),
    sa.Column('is_actual', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contact_person_id'], ['contact_persons.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['factory_model_id'], ['factories_models.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['foreman_id'], ['universal_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mechanic_id'], ['universal_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('factory_number'),
    sa.UniqueConstraint('factory_number', 'registration_number', name='_factory_and_reg_number_uc'),
    sa.UniqueConstraint('registration_number')
    )
    op.create_table('acts_fact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.Column('act_base_id', sa.Integer(), nullable=True),
    sa.Column('step_list_fact', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('foreman_id', sa.Integer(), nullable=True),
    sa.Column('main_mechanic_id', sa.Integer(), nullable=True),
    sa.Column('file', sa.String(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['act_base_id'], ['acts_bases.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['foreman_id'], ['universal_users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['main_mechanic_id'], ['universal_users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['object_id'], ['objects.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['status_id'], ['statuses.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('fault_category_id', sa.Integer(), nullable=True),
    sa.Column('task_text', sa.String(), nullable=True),
    sa.Column('executor_id', sa.Integer(), nullable=True),
    sa.Column('commentary', sa.String(), nullable=True),
    sa.Column('reason_fault_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('in_progress_at', sa.DateTime(), nullable=True),
    sa.Column('done_at', sa.DateTime(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('is_viewed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['universal_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['executor_id'], ['universal_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fault_category_id'], ['fault_category.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['object_id'], ['objects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reason_fault_id'], ['reason_fault.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['status_id'], ['statuses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_photo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('photo', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planned_to',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.String(), nullable=True),
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.Column('january_to_id', sa.Integer(), nullable=True),
    sa.Column('february_to_id', sa.Integer(), nullable=True),
    sa.Column('march_to_id', sa.Integer(), nullable=True),
    sa.Column('april_to_id', sa.Integer(), nullable=True),
    sa.Column('may_to_id', sa.Integer(), nullable=True),
    sa.Column('june_to_id', sa.Integer(), nullable=True),
    sa.Column('july_to_id', sa.Integer(), nullable=True),
    sa.Column('august_to_id', sa.Integer(), nullable=True),
    sa.Column('september_to_id', sa.Integer(), nullable=True),
    sa.Column('october_to_id', sa.Integer(), nullable=True),
    sa.Column('november_to_id', sa.Integer(), nullable=True),
    sa.Column('december_to_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['april_to_id'], ['acts_fact.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['august_to_id'], ['acts_fact.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['december_to_id'], ['acts_fact.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['february_to_id'], ['acts_fact.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['january_to_id'], ['acts_fact.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['july_to_id'], ['acts_fact.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['june_to_id'], ['acts_fact.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['march_to_id'], ['acts_fact.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['may_to_id'], ['acts_fact.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['november_to_id'], ['acts_fact.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['object_id'], ['objects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['october_to_id'], ['acts_fact.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['september_to_id'], ['acts_fact.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', 'object_id', name='_year_object_uc')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planned_to')
    op.drop_table('order_photo')
    op.drop_table('order')
    op.drop_table('acts_fact')
    op.drop_table('objects')
    op.drop_table('organizations')
    op.drop_table('universal_users')
    op.drop_table('contracts')
    op.drop_table('contact_persons')
    op.drop_table('acts_bases')
    op.drop_table('factories_models')
    op.drop_table('company')
    op.drop_table('working_specialty')
    op.drop_table('types_contracts')
    op.drop_table('types_acts')
    op.drop_table('type_objects')
    op.drop_table('sub_steps')
    op.drop_table('steps')
    op.drop_table('statuses')
    op.drop_table('roles')
    op.drop_table('reason_fault')
    op.drop_table('locations')
    op.drop_table('fault_category')
    op.drop_table('divisions')
    op.drop_table('cost_types')
    # ### end Alembic commands ###
