"""empty message

Revision ID: 037eb6268c53
Revises: 425526c4f26e
Create Date: 2022-07-12 10:53:51.673708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '037eb6268c53'
down_revision = '425526c4f26e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'partner_competencies_of_project', ['project_id', 'partner_competencies_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'partner_competencies_of_project', type_='unique')
    # ### end Alembic commands ###
