"""empty message

Revision ID: 03f41b5e769a
Revises: 83499e332d4b
Create Date: 2022-07-08 13:08:53.006416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03f41b5e769a'
down_revision = '83499e332d4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
