"""empty message

Revision ID: 050e1d592303
Revises: 727b8359ab33
Create Date: 2022-07-08 06:53:27.722240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '050e1d592303'
down_revision = '727b8359ab33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
