"""empty message

Revision ID: 058180b5b6dd
Revises: f433bac122cc
Create Date: 2022-07-12 08:00:18.490843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '058180b5b6dd'
down_revision = 'f433bac122cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity_spheres_of_project', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('activity_spheres_of_project', 'sphere_of_activity_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity_spheres_of_project', 'sphere_of_activity_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('activity_spheres_of_project', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
