"""empty message

Revision ID: 0705d3f3b195
Revises: 084dad531f1d
Create Date: 2022-12-05 12:51:28.569117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0705d3f3b195'
down_revision = '084dad531f1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'contracts', ['title'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contracts', type_='unique')
    # ### end Alembic commands ###
