"""empty message

Revision ID: 07eecf78b5cc
Revises: 584b4ec69fd3
Create Date: 2022-10-08 19:01:07.472590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07eecf78b5cc'
down_revision = '584b4ec69fd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
