"""empty message

Revision ID: 084dad531f1d
Revises: bd5efee4804e
Create Date: 2022-12-01 12:24:06.544997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '084dad531f1d'
down_revision = 'bd5efee4804e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
