"""empty message

Revision ID: 0e72d91eddab
Revises: 31d40c11e77e
Create Date: 2022-10-08 06:11:10.233517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e72d91eddab'
down_revision = '31d40c11e77e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
