"""empty message

Revision ID: 0f23b3f5f471
Revises: 8ffb0f731224
Create Date: 2023-01-18 15:57:50.125064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f23b3f5f471'
down_revision = '8ffb0f731224'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acts_bases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factory_model_id', sa.Integer(), nullable=True),
    sa.Column('type_act_id', sa.Integer(), nullable=True),
    sa.Column('step_list', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['factory_model_id'], ['factories_models.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['type_act_id'], ['types_acts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('factory_model_id', 'type_act_id', name='_type_act_factory_model_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('acts_bases')
    # ### end Alembic commands ###
