"""empty message

Revision ID: 103618c04634
Revises: 7b4c19f8c945
Create Date: 2022-07-12 10:13:36.917536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '103618c04634'
down_revision = '7b4c19f8c945'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('partner_competencies_of_project_partner_competencies_id_fkey', 'partner_competencies_of_project', type_='foreignkey')
    op.drop_constraint('partner_competencies_of_project_project_id_fkey', 'partner_competencies_of_project', type_='foreignkey')
    op.create_foreign_key(None, 'partner_competencies_of_project', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'partner_competencies_of_project', 'partner_competencies', ['partner_competencies_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'partner_competencies_of_project', type_='foreignkey')
    op.drop_constraint(None, 'partner_competencies_of_project', type_='foreignkey')
    op.create_foreign_key('partner_competencies_of_project_project_id_fkey', 'partner_competencies_of_project', 'projects', ['project_id'], ['id'])
    op.create_foreign_key('partner_competencies_of_project_partner_competencies_id_fkey', 'partner_competencies_of_project', 'partner_competencies', ['partner_competencies_id'], ['id'])
    # ### end Alembic commands ###
