"""empty message

Revision ID: 12325e630d42
Revises: bb906902cb2a
Create Date: 2022-07-12 08:23:10.049288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12325e630d42'
down_revision = 'bb906902cb2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
