"""empty message

Revision ID: 159edb4eeb00
Revises: 930f9615742d
Create Date: 2022-07-18 11:18:26.006640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '159edb4eeb00'
down_revision = '930f9615742d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
