"""empty message

Revision ID: 1609ad748b4f
Revises: 62a9f007447b
Create Date: 2022-07-08 07:29:36.512323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1609ad748b4f'
down_revision = '62a9f007447b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_location_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'locations', ['location_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_location_id_fkey', 'users', 'locations', ['location_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
