"""empty message

Revision ID: 191442f79a8f
Revises: 7c2a3d1324d6
Create Date: 2022-07-11 12:37:47.737990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '191442f79a8f'
down_revision = '7c2a3d1324d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
