"""remove create old table 2265877af3fd_создание_табл_steps_sub_steps.py

Revision ID: 1a2ec94ba22f
Revises: 22466ac70cee
Create Date: 2023-05-18 11:37:09.971305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a2ec94ba22f'
down_revision = '22466ac70cee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
