"""empty message

Revision ID: 1e2236cf5a85
Revises: dd53a174baec
Create Date: 2022-12-15 12:22:59.526334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e2236cf5a85'
down_revision = 'dd53a174baec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'organizations', ['title'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organizations', type_='unique')
    # ### end Alembic commands ###
