"""empty message

Revision ID: 1f28c19ed105
Revises: 40a77515b5b1
Create Date: 2022-07-18 13:48:19.943741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f28c19ed105'
down_revision = '40a77515b5b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moderators')
    op.create_table('moderators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('tel', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('closed_appeals', sa.Integer(), nullable=True),
    sa.Column('open_appeals', sa.Integer(), nullable=True),
    sa.Column('photo', sa.String(), nullable=True),
    sa.Column('area_of_responsibility_id', sa.Integer(), nullable=True),
    sa.Column('average_first_response_time', sa.String(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['area_of_responsibility_id'], ['area_of_responsibility.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.drop_table('moderator')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moderator',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('login', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tel', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('birthday', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('location_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('closed_appeals', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('open_appeals', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('photo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('area_of_responsibility_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('average_first_response_time', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['area_of_responsibility_id'], ['area_of_responsibility.id'], name='moderator_area_of_responsibility_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name='moderator_location_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='moderator_pkey'),
    sa.UniqueConstraint('login', name='moderator_login_key')
    )
    op.drop_table('moderators')
    # ### end Alembic commands ###
