"""add new table

Revision ID: 1dbc7d7a0c40
Revises: 7a52084d2c29
Create Date: 2024-05-28 17:20:10.267167

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1dbc7d7a0c40'
down_revision = '7a52084d2c29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('area_of_responsibility',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_index('ix_firebasetoken_id', table_name='firebasetoken')
    op.drop_table('firebasetoken')
    op.drop_table('acts_fact_of_mechanic')
    op.add_column('acts_fact', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('acts_fact', sa.Column('finished_at', sa.DateTime(), nullable=True))
    op.add_column('acts_fact', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.drop_constraint('acts_fact_status_id_fkey', 'acts_fact', type_='foreignkey')
    op.drop_constraint('acts_fact_object_id_fkey', 'acts_fact', type_='foreignkey')
    op.drop_constraint('acts_fact_act_base_id_fkey', 'acts_fact', type_='foreignkey')
    op.drop_constraint('acts_fact_main_mechanic_id_fkey', 'acts_fact', type_='foreignkey')
    op.drop_constraint('acts_fact_foreman_id_fkey', 'acts_fact', type_='foreignkey')
    op.create_foreign_key(None, 'acts_fact', 'universal_users', ['foreman_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key(None, 'acts_fact', 'objects', ['object_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key(None, 'acts_fact', 'statuses', ['status_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'acts_fact', 'acts_bases', ['act_base_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key(None, 'acts_fact', 'universal_users', ['main_mechanic_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_column('acts_fact', 'date_create')
    op.drop_column('acts_fact', 'date_finish')
    op.drop_column('acts_fact', 'date_start')
    op.drop_constraint('order_status_id_fkey', 'order', type_='foreignkey')
    op.create_foreign_key(None, 'order', 'statuses', ['status_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.create_foreign_key('order_status_id_fkey', 'order', 'statuses', ['status_id'], ['id'], ondelete='SET NULL')
    op.add_column('acts_fact', sa.Column('date_start', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('acts_fact', sa.Column('date_finish', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('acts_fact', sa.Column('date_create', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'acts_fact', type_='foreignkey')
    op.drop_constraint(None, 'acts_fact', type_='foreignkey')
    op.drop_constraint(None, 'acts_fact', type_='foreignkey')
    op.drop_constraint(None, 'acts_fact', type_='foreignkey')
    op.drop_constraint(None, 'acts_fact', type_='foreignkey')
    op.create_foreign_key('acts_fact_foreman_id_fkey', 'acts_fact', 'universal_users', ['foreman_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('acts_fact_main_mechanic_id_fkey', 'acts_fact', 'universal_users', ['main_mechanic_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('acts_fact_act_base_id_fkey', 'acts_fact', 'acts_bases', ['act_base_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('acts_fact_object_id_fkey', 'acts_fact', 'objects', ['object_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('acts_fact_status_id_fkey', 'acts_fact', 'statuses', ['status_id'], ['id'], ondelete='SET NULL')
    op.drop_column('acts_fact', 'started_at')
    op.drop_column('acts_fact', 'finished_at')
    op.drop_column('acts_fact', 'created_at')
    op.create_table('acts_fact_of_mechanic',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('act_fact_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('mechanic_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['act_fact_id'], ['acts_fact.id'], name='acts_fact_of_mechanic_act_fact_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mechanic_id'], ['universal_users.id'], name='acts_fact_of_mechanic_mechanic_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='acts_fact_of_mechanic_pkey'),
    sa.UniqueConstraint('act_fact_id', 'mechanic_id', name='acts_fact_of_mechanic_act_fact_id_mechanic_id_key')
    )
    op.create_table('firebasetoken',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('value', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('device_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='firebasetoken_pkey')
    )
    op.create_index('ix_firebasetoken_id', 'firebasetoken', ['id'], unique=False)
    op.drop_table('area_of_responsibility')
    # ### end Alembic commands ###
