"""remove stage_of_implementation

Revision ID: 22466ac70cee
Revises: 73224c4c985e
Create Date: 2023-05-18 11:26:15.376247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22466ac70cee'
down_revision = '73224c4c985e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stage_of_implementation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stage_of_implementation',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='stage_of_implementation_pkey'),
    sa.UniqueConstraint('name', name='stage_of_implementation_name_key')
    )
    # ### end Alembic commands ###
