"""создание табл steps, sub_steps

Revision ID: 2265877af3fd
Revises: b39aafb5e1c4
Create Date: 2023-03-27 14:28:50.803524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2265877af3fd'
down_revision = 'b39aafb5e1c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_spheres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('picture', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('activity_spheres_of_project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('activity_of_sphere_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_of_sphere_id'], ['activity_spheres.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'activity_of_sphere_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity_spheres_of_project')
    op.drop_table('activity_spheres')
    # ### end Alembic commands ###
