"""empty message

Revision ID: 29d971855d9d
Revises: 52c285a00ff0
Create Date: 2022-11-02 11:10:25.528749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29d971855d9d'
down_revision = '52c285a00ff0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('universal_users_email_key', 'universal_users', type_='unique')
    op.create_unique_constraint('_email_is_actual_uc', 'universal_users', ['email', 'is_actual'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_email_is_actual_uc', 'universal_users', type_='unique')
    op.create_unique_constraint('universal_users_email_key', 'universal_users', ['email'])
    # ### end Alembic commands ###
