"""empty message

Revision ID: 2a97a5865207
Revises: 408d2eb6ae33
Create Date: 2022-10-24 11:26:53.327747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a97a5865207'
down_revision = '408d2eb6ae33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'email')
    # ### end Alembic commands ###
