"""empty message

Revision ID: 2d3c524627e2
Revises: b52f09dbbc18
Create Date: 2022-12-01 11:06:07.371252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d3c524627e2'
down_revision = 'b52f09dbbc18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
