"""empty message

Revision ID: 2d6363ebd366
Revises: e08bc6e151d8
Create Date: 2022-07-08 07:53:34.964746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d6363ebd366'
down_revision = 'e08bc6e151d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_location_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'locations', ['location_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_location_id_fkey', 'users', 'locations', ['location_id'], ['id'])
    # ### end Alembic commands ###
