"""empty message

Revision ID: 31be2dc84a4e
Revises: 07eecf78b5cc
Create Date: 2022-10-20 12:13:54.039796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31be2dc84a4e'
down_revision = '07eecf78b5cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('name_director', sa.String(), nullable=True),
    sa.Column('phone_director', sa.String(), nullable=True),
    sa.Column('phone_office', sa.String(), nullable=True),
    sa.Column('phone_dispatcher', sa.String(), nullable=True),
    sa.Column('phone_accountant', sa.String(), nullable=True),
    sa.Column('photo', sa.String(), nullable=True),
    sa.Column('site', sa.String(), nullable=True),
    sa.Column('id_actual', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('type_objects',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('factories_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_object_id', sa.Integer(), nullable=True),
    sa.Column('factory', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['type_object_id'], ['type_objects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type_object_id', 'factory', 'model', name='_type_object_factory_model_uc')
    )
    op.drop_table('moderators')
    op.drop_table('super_users')
    op.drop_table('mechanic')
    op.add_column('company', sa.Column('contract_file', sa.String(), nullable=True))
    op.add_column('company', sa.Column('validity_period', sa.Date(), nullable=True))
    op.add_column('company', sa.Column('type_contract', sa.String(), nullable=True))
    op.add_column('divisions', sa.Column('title', sa.String(), nullable=True))
    op.add_column('divisions', sa.Column('photo', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'divisions', ['title'])
    op.drop_constraint('divisions_company_id_fkey', 'divisions', type_='foreignkey')
    op.drop_column('divisions', 'cont_address')
    op.drop_column('divisions', 'cont_phone')
    op.drop_column('divisions', 'company_id')
    op.drop_column('divisions', 'cont_person_name')
    op.drop_column('divisions', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('divisions', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('divisions', sa.Column('cont_person_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('divisions', sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('divisions', sa.Column('cont_phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('divisions', sa.Column('cont_address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('divisions_company_id_fkey', 'divisions', 'company', ['company_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'divisions', type_='unique')
    op.drop_column('divisions', 'photo')
    op.drop_column('divisions', 'title')
    op.drop_column('company', 'type_contract')
    op.drop_column('company', 'validity_period')
    op.drop_column('company', 'contract_file')
    op.create_table('mechanic',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('contact_phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('birthday', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('photo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('location_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_commissioning_engineer', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_actual', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name='mechanic_location_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='mechanic_pkey'),
    sa.UniqueConstraint('email', name='mechanic_email_key')
    )
    op.create_table('super_users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('contact_phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('birthday', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('photo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_super_user', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('location_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name='super_users_location_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='super_users_pkey'),
    sa.UniqueConstraint('email', name='super_users_email_key')
    )
    op.create_table('moderators',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('login', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tel', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('birthday', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('location_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('photo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('area_of_responsibility_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('average_first_response_time', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['area_of_responsibility_id'], ['area_of_responsibility.id'], name='moderators_area_of_responsibility_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name='moderators_location_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='moderators_pkey'),
    sa.UniqueConstraint('login', name='moderators_login_key')
    )
    op.drop_table('factories_models')
    op.drop_table('type_objects')
    op.drop_table('organizations')
    # ### end Alembic commands ###
