"""empty message

Revision ID: 384c3f901a00
Revises: 0705d3f3b195
Create Date: 2022-12-14 07:10:39.371046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '384c3f901a00'
down_revision = '0705d3f3b195'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('universal_users', sa.Column('date_of_employment', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('universal_users', 'date_of_employment')
    # ### end Alembic commands ###
