"""empty message

Revision ID: 3a3cc15111a9
Revises: e04dbed80881
Create Date: 2023-01-25 10:49:10.887655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a3cc15111a9'
down_revision = 'e04dbed80881'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
