"""empty message

Revision ID: 405942087b64
Revises: e0eefc8ea9ed
Create Date: 2023-02-17 11:12:23.903727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '405942087b64'
down_revision = 'e0eefc8ea9ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
