"""empty message

Revision ID: 408d2eb6ae33
Revises: fe321752ffa2
Create Date: 2022-10-24 09:02:32.861642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '408d2eb6ae33'
down_revision = 'fe321752ffa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
