"""empty message

Revision ID: 425526c4f26e
Revises: 55ce78af1f56
Create Date: 2022-07-12 10:41:41.096658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '425526c4f26e'
down_revision = '55ce78af1f56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uniq_couple_1', 'activity_spheres_of_project', ['project_id', 'activity_of_sphere_id'])
    op.drop_constraint('activity_spheres_of_project_activity_of_sphere_id_fkey', 'activity_spheres_of_project', type_='foreignkey')
    op.drop_constraint('activity_spheres_of_project_project_id_fkey', 'activity_spheres_of_project', type_='foreignkey')
    op.create_foreign_key(None, 'activity_spheres_of_project', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'activity_spheres_of_project', 'activity_spheres', ['activity_of_sphere_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'activity_spheres_of_project', type_='foreignkey')
    op.drop_constraint(None, 'activity_spheres_of_project', type_='foreignkey')
    op.create_foreign_key('activity_spheres_of_project_project_id_fkey', 'activity_spheres_of_project', 'projects', ['project_id'], ['id'])
    op.create_foreign_key('activity_spheres_of_project_activity_of_sphere_id_fkey', 'activity_spheres_of_project', 'activity_spheres', ['activity_of_sphere_id'], ['id'])
    op.drop_constraint('uniq_couple', 'activity_spheres_of_project', type_='unique')
    # ### end Alembic commands ###
