"""empty message

Revision ID: 43928a9b8655
Revises: b560f15d57ab
Create Date: 2022-12-26 16:53:49.013305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43928a9b8655'
down_revision = 'b560f15d57ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('objects', sa.Column('geo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('objects', 'geo')
    # ### end Alembic commands ###
