"""empty message

Revision ID: 4e0fb23ab538
Revises: 3e1829703835
Create Date: 2022-07-15 07:45:09.058043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e0fb23ab538'
down_revision = '3e1829703835'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'projects', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='unique')
    # ### end Alembic commands ###
