"""empty message

Revision ID: 4f7fb7c7d84c
Revises: 191442f79a8f
Create Date: 2022-07-11 14:10:18.057892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f7fb7c7d84c'
down_revision = '191442f79a8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
