"""upgrade alembic for server

Revision ID: 511d4f3eaa9e
Revises: 916e125ce1f5
Create Date: 2022-11-29 11:07:36.730678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '511d4f3eaa9e'
down_revision = '916e125ce1f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
