"""empty message

Revision ID: 52c285a00ff0
Revises: 764c929e1d92
Create Date: 2022-10-27 10:11:23.162130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52c285a00ff0'
down_revision = '764c929e1d92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('universal_users', sa.Column('qualification_file', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('universal_users', 'qualification_file')
    # ### end Alembic commands ###
