"""empty message

Revision ID: 5d903ed44e58
Revises: 1609ad748b4f
Create Date: 2022-07-08 07:35:37.262442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d903ed44e58'
down_revision = '1609ad748b4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
