"""empty message

Revision ID: 5e86e6b96fd7
Revises: 2a97a5865207
Create Date: 2022-10-24 11:29:02.533489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e86e6b96fd7'
down_revision = '2a97a5865207'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('types_contracts',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('contact_persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('photo', sa.String(), nullable=True),
    sa.Column('is_actual', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('validity_period', sa.Date(), nullable=True),
    sa.Column('type_contract_id', sa.Integer(), nullable=True),
    sa.Column('file', sa.String(), nullable=True),
    sa.Column('is_actual', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['type_contract_id'], ['types_contracts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('objects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('division_id', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('factory_model_id', sa.Integer(), nullable=True),
    sa.Column('factory_number', sa.String(), nullable=True),
    sa.Column('registration_number', sa.String(), nullable=True),
    sa.Column('number_of_stops', sa.Integer(), nullable=True),
    sa.Column('lifting_heights', sa.Integer(), nullable=True),
    sa.Column('load_capacity', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('cost_nds', sa.Integer(), nullable=True),
    sa.Column('cost_no_nds', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('contact_person_id', sa.Integer(), nullable=True),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('date_inspection', sa.Date(), nullable=True),
    sa.Column('planned_inspection', sa.Date(), nullable=True),
    sa.Column('period_inspection', sa.Date(), nullable=True),
    sa.Column('foreman_id', sa.Integer(), nullable=True),
    sa.Column('mechanic_id', sa.Integer(), nullable=True),
    sa.Column('letter_of_appointment', sa.String(), nullable=True),
    sa.Column('acceptance_certificate', sa.String(), nullable=True),
    sa.Column('act_pto', sa.String(), nullable=True),
    sa.Column('is_actual', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contact_person_id'], ['contact_persons.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['factory_model_id'], ['factories_models.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['foreman_id'], ['universal_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mechanic_id'], ['universal_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('factory_number'),
    sa.UniqueConstraint('registration_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('objects')
    op.drop_table('contracts')
    op.drop_table('contact_persons')
    op.drop_table('types_contracts')
    # ### end Alembic commands ###
