"""empty message

Revision ID: 65de75074d7c
Revises: d7f9eb91b03e
Create Date: 2023-05-18 09:59:59.562609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65de75074d7c'
down_revision = 'd7f9eb91b03e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
