"""empty message

Revision ID: 665d9cc9cafb
Revises: b17c1e54729b
Create Date: 2022-12-01 12:08:12.480219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '665d9cc9cafb'
down_revision = 'b17c1e54729b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('cost_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'contracts', 'cost_types', ['cost_type_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contracts', type_='foreignkey')
    op.drop_column('contracts', 'cost_type_id')
    # ### end Alembic commands ###
