"""empty message

Revision ID: 707bb6c23414
Revises: c91d72b5d26c
Create Date: 2022-07-15 06:45:28.707742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '707bb6c23414'
down_revision = 'c91d72b5d26c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'projects', ['user_id', 'name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='unique')
    # ### end Alembic commands ###
