"""empty message

Revision ID: 70c9d3cbf506
Revises: 058180b5b6dd
Create Date: 2022-07-12 08:03:37.275057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70c9d3cbf506'
down_revision = '058180b5b6dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_spheres_of_project', sa.Column('activity_of_sphere_id', sa.Integer(), nullable=False))
    op.drop_constraint('activity_spheres_of_project_sphere_of_activity_id_fkey', 'activity_spheres_of_project', type_='foreignkey')
    op.create_foreign_key(None, 'activity_spheres_of_project', 'activity_spheres', ['activity_of_sphere_id'], ['id'])
    op.drop_column('activity_spheres_of_project', 'sphere_of_activity_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_spheres_of_project', sa.Column('sphere_of_activity_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'activity_spheres_of_project', type_='foreignkey')
    op.create_foreign_key('activity_spheres_of_project_sphere_of_activity_id_fkey', 'activity_spheres_of_project', 'activity_spheres', ['sphere_of_activity_id'], ['id'])
    op.drop_column('activity_spheres_of_project', 'activity_of_sphere_id')
    # ### end Alembic commands ###
