"""empty message

Revision ID: 727b8359ab33
Revises: 8ac97126e72e
Create Date: 2022-07-08 06:39:35.985625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '727b8359ab33'
down_revision = '8ac97126e72e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
