"""empty message

Revision ID: 764c929e1d92
Revises: aa34844c6abd
Create Date: 2022-10-25 15:01:43.374010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '764c929e1d92'
down_revision = 'aa34844c6abd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contact_persons', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'contact_persons', ['phone'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contact_persons', type_='unique')
    op.alter_column('contact_persons', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
