"""add planned_to 2

Revision ID: 7a52084d2c29
Revises: 99f4a372765f
Create Date: 2023-09-04 13:50:20.438310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a52084d2c29'
down_revision = '99f4a372765f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planned_to',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.String(), nullable=True),
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.Column('january_to_id', sa.Integer(), nullable=True),
    sa.Column('february_to_id', sa.Integer(), nullable=True),
    sa.Column('march_to_id', sa.Integer(), nullable=True),
    sa.Column('april_to_id', sa.Integer(), nullable=True),
    sa.Column('may_to_id', sa.Integer(), nullable=True),
    sa.Column('june_to_id', sa.Integer(), nullable=True),
    sa.Column('july_to_id', sa.Integer(), nullable=True),
    sa.Column('august_to_id', sa.Integer(), nullable=True),
    sa.Column('september_to_id', sa.Integer(), nullable=True),
    sa.Column('october_to_id', sa.Integer(), nullable=True),
    sa.Column('november_to_id', sa.Integer(), nullable=True),
    sa.Column('december_to_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['april_to_id'], ['acts_fact.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['august_to_id'], ['acts_fact.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['december_to_id'], ['acts_fact.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['february_to_id'], ['acts_fact.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['january_to_id'], ['acts_fact.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['july_to_id'], ['acts_fact.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['june_to_id'], ['acts_fact.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['march_to_id'], ['acts_fact.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['may_to_id'], ['acts_fact.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['november_to_id'], ['acts_fact.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['object_id'], ['objects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['october_to_id'], ['acts_fact.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['september_to_id'], ['acts_fact.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', 'object_id', name='_year_object_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planned_to')
    # ### end Alembic commands ###
