"""empty message

Revision ID: 7b4c19f8c945
Revises: 12325e630d42
Create Date: 2022-07-12 08:25:57.976511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b4c19f8c945'
down_revision = '12325e630d42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uniq_couple', 'partner_competencies_of_project', ['project_id', 'partner_competencies_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uniq_couple', 'partner_competencies_of_project', type_='unique')
    # ### end Alembic commands ###
