"""empty message

Revision ID: 7c2a3d1324d6
Revises: daae6507f2ae
Create Date: 2022-07-08 13:39:09.132397

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7c2a3d1324d6'
down_revision = 'daae6507f2ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('x_real_ip', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('accept_language', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('detected_os', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_id'), 'device', ['id'], unique=False)
    op.create_table('firebasetoken',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_firebasetoken_id'), 'firebasetoken', ['id'], unique=False)
    op.drop_column('users', 'accept_language')
    op.drop_column('users', 'user_agent')
    op.drop_column('users', 'x_real_ip')
    op.drop_column('users', 'x_firebase_token')
    op.drop_column('users', 'host')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('host', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('x_firebase_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('x_real_ip', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('user_agent', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('accept_language', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_firebasetoken_id'), table_name='firebasetoken')
    op.drop_table('firebasetoken')
    op.drop_index(op.f('ix_device_id'), table_name='device')
    op.drop_table('device')
    # ### end Alembic commands ###
