"""empty message

Revision ID: 7e6e200b6bbf
Revises: 159edb4eeb00
Create Date: 2022-07-18 11:26:25.897742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e6e200b6bbf'
down_revision = '159edb4eeb00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('area_of_responsibility',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('area_of_responsibility')
    # ### end Alembic commands ###
