"""empty message

Revision ID: 83499e332d4b
Revises: 2d6363ebd366
Create Date: 2022-07-08 12:58:31.179447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83499e332d4b'
down_revision = '2d6363ebd366'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('host', sa.String(), nullable=True))
    op.add_column('users', sa.Column('x_real_ip', sa.String(), nullable=True))
    op.add_column('users', sa.Column('accept_language', sa.String(), nullable=True))
    op.add_column('users', sa.Column('user_agent', sa.String(), nullable=True))
    op.add_column('users', sa.Column('x_firebase_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'x_firebase_token')
    op.drop_column('users', 'user_agent')
    op.drop_column('users', 'accept_language')
    op.drop_column('users', 'x_real_ip')
    op.drop_column('users', 'host')
    # ### end Alembic commands ###
