"""empty message

Revision ID: 8a5d7dd168ea
Revises: 994309b9be8a
Create Date: 2022-07-19 07:29:05.419931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a5d7dd168ea'
down_revision = '994309b9be8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
