"""empty message

Revision ID: 8ac97126e72e
Revises: b761c40d1371
Create Date: 2022-07-07 11:57:39.275437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ac97126e72e'
down_revision = 'b761c40d1371'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('users', sa.Column('location_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'locations', ['location_id'], ['id'])
    op.drop_column('users', 'location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'location_id')
    op.drop_table('locations')
    # ### end Alembic commands ###
