"""empty message

Revision ID: 8ffb0f731224
Revises: 2ac8a151b242
Create Date: 2023-01-18 15:53:52.905017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ffb0f731224'
down_revision = '2ac8a151b242'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
