"""empty message

Revision ID: 916e125ce1f5
Revises: 29d971855d9d
Create Date: 2022-11-21 11:58:26.751411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '916e125ce1f5'
down_revision = '29d971855d9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('site', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'site')
    # ### end Alembic commands ###
