"""initial

Revision ID: 9203bc727c7e
Revises: e52e45a5e702
Create Date: 2023-07-18 11:22:57.207471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9203bc727c7e'
down_revision = 'e52e45a5e702'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
