"""initial

Revision ID: 925ab90661a6
Revises: 9203bc727c7e
Create Date: 2023-07-18 18:46:31.097283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '925ab90661a6'
down_revision = '9203bc727c7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
