"""empty message

Revision ID: 930f9615742d
Revises: 4e0fb23ab538
Create Date: 2022-07-18 06:42:20.729071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '930f9615742d'
down_revision = '4e0fb23ab538'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'partner_competencies', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'partner_competencies', type_='unique')
    # ### end Alembic commands ###
