"""initial

Revision ID: 962d4abc93a6
Revises: 925ab90661a6
Create Date: 2023-07-19 12:30:38.330230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '962d4abc93a6'
down_revision = '925ab90661a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
