"""empty message

Revision ID: 98b6ef7886fe
Revises: 43928a9b8655
Create Date: 2023-01-13 14:49:18.635241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98b6ef7886fe'
down_revision = '43928a9b8655'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_factory_and_reg_number_uc', 'objects', ['factory_number', 'registration_number'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_factory_and_reg_number_uc', 'objects', type_='unique')
    # ### end Alembic commands ###
