"""empty message

Revision ID: 994309b9be8a
Revises: c121ecd586dd
Create Date: 2022-07-19 07:14:08.190862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '994309b9be8a'
down_revision = 'c121ecd586dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('projects_user_id_fkey', 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key('projects_user_id_fkey', 'projects', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
