"""empty message

Revision ID: a5d5a0ce5fa8
Revises: c1ef8cac13a7
Create Date: 2022-07-19 06:46:48.133932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5d5a0ce5fa8'
down_revision = 'c1ef8cac13a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('device_user_id_fkey', 'device', type_='foreignkey')
    op.create_foreign_key(None, 'device', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'device', type_='foreignkey')
    op.create_foreign_key('device_user_id_fkey', 'device', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
