"""empty message

Revision ID: a90fe0bc096d
Revises: 7e6e200b6bbf
Create Date: 2022-07-18 12:33:42.455516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a90fe0bc096d'
down_revision = '7e6e200b6bbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
