"""empty message

Revision ID: aa34844c6abd
Revises: 5e86e6b96fd7
Create Date: 2022-10-24 11:40:55.736451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa34844c6abd'
down_revision = '5e86e6b96fd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'contract_file')
    op.drop_column('company', 'validity_period')
    op.drop_column('company', 'type_contract')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('type_contract', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('company', sa.Column('validity_period', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('company', sa.Column('contract_file', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
