"""empty message

Revision ID: b17c1e54729b
Revises: 32664d76ba05
Create Date: 2022-12-01 11:22:41.135144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b17c1e54729b'
down_revision = '32664d76ba05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
