"""empty message

Revision ID: b39aafb5e1c4
Revises: 405942087b64
Create Date: 2023-02-17 15:52:18.786646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b39aafb5e1c4'
down_revision = '405942087b64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
