"""upgrade alembic for server 2

Revision ID: b52f09dbbc18
Revises: 511d4f3eaa9e
Create Date: 2022-11-29 18:10:51.632865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b52f09dbbc18'
down_revision = '511d4f3eaa9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
