"""empty message

Revision ID: b560f15d57ab
Revises: 1e2236cf5a85
Create Date: 2022-12-15 14:08:27.071356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b560f15d57ab'
down_revision = '1e2236cf5a85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
