"""empty message

Revision ID: b5d4cb93f34d
Revises: 8447dcc416df
Create Date: 2022-09-05 20:14:06.419927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5d4cb93f34d'
down_revision = '8447dcc416df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('super_users', sa.Column('location_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'super_users', 'locations', ['location_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'super_users', type_='foreignkey')
    op.drop_column('super_users', 'location_id')
    # ### end Alembic commands ###
