"""empty message

Revision ID: bb906902cb2a
Revises: 70c9d3cbf506
Create Date: 2022-07-12 08:14:08.896151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb906902cb2a'
down_revision = '70c9d3cbf506'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
