"""empty message

Revision ID: bd5efee4804e
Revises: 665d9cc9cafb
Create Date: 2022-12-01 12:21:41.424740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd5efee4804e'
down_revision = '665d9cc9cafb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
