"""empty message

Revision ID: c121ecd586dd
Revises: a5d5a0ce5fa8
Create Date: 2022-07-19 07:06:27.637391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c121ecd586dd'
down_revision = 'a5d5a0ce5fa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
