"""empty message

Revision ID: c1ef8cac13a7
Revises: cb35e83afbf6
Create Date: 2022-07-18 13:55:47.292552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1ef8cac13a7'
down_revision = 'cb35e83afbf6'
branch_labels = None
depends_on = None


def upgrade():
    op.drop_table('moderators')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moderators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('tel', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('closed_appeals', sa.Integer(), nullable=True),
    sa.Column('open_appeals', sa.Integer(), nullable=True),
    sa.Column('photo', sa.String(), nullable=True),
    sa.Column('area_of_responsibility_id', sa.Integer(), nullable=True),
    sa.Column('average_first_response_time', sa.Integer(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['area_of_responsibility_id'], ['area_of_responsibility.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moderators')
    # ### end Alembic commands ###
