"""empty message

Revision ID: c72822195249
Revises: 0b015ab6bc7d
Create Date: 2022-07-19 07:33:10.119575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c72822195249'
down_revision = '0b015ab6bc7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
