"""empty message

Revision ID: cb35e83afbf6
Revises: 1f28c19ed105
Create Date: 2022-07-18 13:51:53.755645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb35e83afbf6'
down_revision = '1f28c19ed105'
branch_labels = None
depends_on = None


def upgrade():
   pass
    # # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('moderators', 'average_first_response_time',
    #            existing_type=sa.VARCHAR(),
    #            type_=sa.Integer(),
    #            existing_nullable=True)
    # # ### end Alembic commands ###


def downgrade():
    pass
    # # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('moderators', 'average_first_response_time',
    #            existing_type=sa.Integer(),
    #            type_=sa.VARCHAR(),
    #            existing_nullable=True)
    # # ### end Alembic commands ###
