"""empty message

Revision ID: cd23e9cb70cb
Revises: 707bb6c23414
Create Date: 2022-07-15 07:06:59.279473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd23e9cb70cb'
down_revision = '707bb6c23414'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
