"""empty message

Revision ID: d174413a8b34
Revises: e1de6503f7da
Create Date: 2022-08-23 12:25:37.258603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd174413a8b34'
down_revision = 'e1de6503f7da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
