"""empty message

Revision ID: d4caa590f9ed
Revises: 0698164dde34
Create Date: 2022-09-29 11:14:31.969212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4caa590f9ed'
down_revision = '0698164dde34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('director_name', sa.String(), nullable=True),
    sa.Column('cont_phone', sa.String(), nullable=True),
    sa.Column('cont_address', sa.String(), nullable=True),
    sa.Column('photo', sa.String(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('is_actual', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('divisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('cont_person_name', sa.String(), nullable=True),
    sa.Column('cont_phone', sa.String(), nullable=True),
    sa.Column('cont_address', sa.String(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('is_actual', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('universaluser', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'universaluser', 'company', ['company_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'universaluser', type_='foreignkey')
    op.drop_column('universaluser', 'company_id')
    op.drop_table('divisions')
    op.drop_table('company')
    # ### end Alembic commands ###
