"""empty message

Revision ID: d60eb250b95d
Revises: 3908dc3841ca
Create Date: 2023-01-25 03:36:19.223259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd60eb250b95d'
down_revision = '3908dc3841ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acts_fact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.Column('act_base_id', sa.Integer(), nullable=True),
    sa.Column('step_list_fact', sa.String(), nullable=True),
    sa.Column('date_create', sa.Date(), nullable=True),
    sa.Column('date_start', sa.Date(), nullable=True),
    sa.Column('date_finish', sa.Date(), nullable=True),
    sa.Column('foreman_id', sa.Integer(), nullable=True),
    sa.Column('main_mechanic_id', sa.Integer(), nullable=True),
    sa.Column('file', sa.String(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['act_base_id'], ['acts_bases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['foreman_id'], ['universal_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['main_mechanic_id'], ['universal_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['object_id'], ['objects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['status_id'], ['statuses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('acts_fact')
    # ### end Alembic commands ###
