"""empty message

Revision ID: daae6507f2ae
Revises: 03f41b5e769a
Create Date: 2022-07-08 13:12:07.150971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daae6507f2ae'
down_revision = '03f41b5e769a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
