"""empty message

Revision ID: dd53a174baec
Revises: 384c3f901a00
Create Date: 2022-12-15 10:27:04.861735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd53a174baec'
down_revision = '384c3f901a00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('director_id', sa.Integer(), nullable=True))
    op.add_column('organizations', sa.Column('email', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('address', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('is_actual', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'organizations', 'universal_users', ['director_id'], ['id'], ondelete='SET NULL')
    op.drop_column('organizations', 'id_actual')
    op.drop_column('organizations', 'name_director')
    op.drop_column('organizations', 'phone_director')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('phone_director', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('organizations', sa.Column('name_director', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('organizations', sa.Column('id_actual', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'organizations', type_='foreignkey')
    op.drop_column('organizations', 'is_actual')
    op.drop_column('organizations', 'address')
    op.drop_column('organizations', 'email')
    op.drop_column('organizations', 'director_id')
    # ### end Alembic commands ###
