"""удалил 5 таблиц которые больше не задействуются

Revision ID: dd975f0d2a3d
Revises: 30e87407a1b7
Create Date: 2023-03-27 14:57:44.982172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd975f0d2a3d'
down_revision = '30e87407a1b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
