"""empty message

Revision ID: dda050fd42ca
Revises: d174413a8b34
Create Date: 2022-08-23 12:54:02.460983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dda050fd42ca'
down_revision = 'd174413a8b34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
