"""empty message

Revision ID: dde3ef34935c
Revises: 4f7fb7c7d84c
Create Date: 2022-07-11 14:50:31.060223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dde3ef34935c'
down_revision = '4f7fb7c7d84c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
