"""empty message

Revision ID: e04dbed80881
Revises: d60eb250b95d
Create Date: 2023-01-25 10:43:34.526766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e04dbed80881'
down_revision = 'd60eb250b95d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acts_fact_of_mechanic_id',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('act_fact_id', sa.Integer(), nullable=False),
    sa.Column('mechanic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['act_fact_id'], ['acts_fact.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mechanic_id'], ['universal_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('act_fact_id', 'mechanic_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('acts_fact_of_mechanic_id')
    # ### end Alembic commands ###
