"""empty message

Revision ID: e08bc6e151d8
Revises: 5d903ed44e58
Create Date: 2022-07-08 07:38:34.455448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e08bc6e151d8'
down_revision = '5d903ed44e58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
