"""empty message

Revision ID: e0eefc8ea9ed
Revises: a067234b18ec
Create Date: 2023-02-13 13:20:47.881351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0eefc8ea9ed'
down_revision = 'a067234b18ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('objects', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('objects', 'name')
    # ### end Alembic commands ###
