"""empty message

Revision ID: e1de6503f7da
Revises: 86161ba9224e
Create Date: 2022-07-19 13:35:46.697932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1de6503f7da'
down_revision = '86161ba9224e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moderators', sa.Column('password', sa.String(), nullable=True))
    op.drop_column('moderators', 'key')
    op.drop_column('moderators', 'closed_appeals')
    op.drop_column('moderators', 'open_appeals')
    op.drop_column('moderators', 'salt')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moderators', sa.Column('salt', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('moderators', sa.Column('open_appeals', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('moderators', sa.Column('closed_appeals', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('moderators', sa.Column('key', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('moderators', 'password')
    # ### end Alembic commands ###
