"""empty message

Revision ID: ebba240b6d43
Revises: c0fdf8fb48f7
Create Date: 2022-07-18 13:13:27.288417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebba240b6d43'
down_revision = 'c0fdf8fb48f7'
branch_labels = None
depends_on = None


def upgrade():
   pass
    # # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('moderators', 'closed_appeals',
    #            existing_type=sa.VARCHAR(),
    #            type_=sa.Integer(),
    #            existing_nullable=True)
    # op.alter_column('moderators', 'open_appeals',
    #            existing_type=sa.VARCHAR(),
    #            type_=sa.Integer(),
    #            existing_nullable=True)
    # # ### end Alembic commands ###


def downgrade():
    pass
    # # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('moderators', 'open_appeals',
    #            existing_type=sa.Integer(),
    #            type_=sa.VARCHAR(),
    #            existing_nullable=True)
    # op.alter_column('moderators', 'closed_appeals',
    #            existing_type=sa.Integer(),
    #            type_=sa.VARCHAR(),
    #            existing_nullable=True)
    # # ### end Alembic commands ###
