"""empty message

Revision ID: f433bac122cc
Revises: fb0232ec977b
Create Date: 2022-07-12 07:58:15.065883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f433bac122cc'
down_revision = 'fb0232ec977b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('partner_competencies_of_project', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('partner_competencies_of_project', 'partner_competencies_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('partner_competencies_of_project', 'partner_competencies_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('partner_competencies_of_project', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
