"""empty message

Revision ID: fa8d8b734d8b
Revises: b5d4cb93f34d
Create Date: 2022-09-21 12:35:37.090942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa8d8b734d8b'
down_revision = 'b5d4cb93f34d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
