"""empty message

Revision ID: fb0232ec977b
Revises: dde3ef34935c
Create Date: 2022-07-12 07:13:19.349427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb0232ec977b'
down_revision = 'dde3ef34935c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_spheres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('picture', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('partner_competencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stage_of_implementation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('stages_of_implementation_id', sa.Integer(), nullable=True),
    sa.Column('budget', sa.Integer(), nullable=True),
    sa.Column('partners_share', sa.Integer(), nullable=True),
    sa.Column('about_the_project', sa.String(), nullable=True),
    sa.Column('site', sa.String(), nullable=True),
    sa.Column('photo_main', sa.String(), nullable=True),
    sa.Column('photo_1', sa.String(), nullable=True),
    sa.Column('photo_2', sa.String(), nullable=True),
    sa.Column('about_me', sa.String(), nullable=True),
    sa.Column('work_experience', sa.String(), nullable=True),
    sa.Column('my_strengths', sa.String(), nullable=True),
    sa.Column('opening_hours', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['stages_of_implementation_id'], ['stage_of_implementation.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity_spheres_of_project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('sphere_of_activity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['sphere_of_activity_id'], ['activity_spheres.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partner_competencies_of_project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('partner_competencies_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['partner_competencies_id'], ['partner_competencies.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('partner_competencies_of_project')
    op.drop_table('activity_spheres_of_project')
    op.drop_table('projects')
    op.drop_table('stage_of_implementation')
    op.drop_table('partner_competencies')
    op.drop_table('activity_spheres')
    # ### end Alembic commands ###
