"""empty message

Revision ID: fe321752ffa2
Revises: 31be2dc84a4e
Create Date: 2022-10-24 08:50:53.942880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe321752ffa2'
down_revision = '31be2dc84a4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('universal_users', sa.Column('division_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'universal_users', 'divisions', ['division_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'universal_users', type_='foreignkey')
    op.drop_column('universal_users', 'division_id')
    # ### end Alembic commands ###
