"""init

Revision ID: 99f4a372765f
Revises: d7c2a3fc7dde
Create Date: 2023-08-01 16:41:43.342413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99f4a372765f'
down_revision = 'd7c2a3fc7dde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
